In [19]:
import pandas as pd
import re
from datetime import datetime

import ProjectA_ElectronicsStore_TransactionalData as pA
import helper_functions as hf

import logging

# logging.basicConfig(level=logging.DEBUG, filename='G:\\My Drive\\DANIELS ECOSYSTEM\\extracurricularActivities\\DataScience\\Projects\\Transactional Retail Dataset of Electronics Store\\tmp.log')

In [3]:
df = pd.read_csv(hf.create_dir('G:\My Drive\DANIELS ECOSYSTEM\extracurricularActivities\DataScience\datasets\Transactional Retail Dataset of Electronics Store', 'test_output.csv'))
# hf.create_dir('G:\My Drive\DANIELS ECOSYSTEM\extracurricularActivities\DataScience\datasets\Transactional Retail Dataset of Electronics Store', 'test_output.csv')
df.head()

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
0,ORD473815,ID0588198721,2019-03-13,Nickolson,"[('Thunder line', 1), ('pearTV', 1)]",8490,66.07,-37.812137,144.973992,5,8131.57,Autumn,False,0.8182,awesome phone! great phone! the screen is a ni...,True
1,ORD347594,ID0332796790,2019-04-01,Bakers,"[('Lucent 330S', 2), ('pearTV', 2), ('iAssist ...",35205,73.58,-37.808563,145.000167,10,31758.08,Summer,True,0.4624,not as advertised was not actually unlocked an...,False
2,ORD293148,ID1681675856,2019-12-09,Nickolson,"[('Toshika 750', 1), ('Candle Inferno', 2)]",5180,80.53,-37.809841,144.976329,25,3965.53,Spring,False,1.1423,great build qualitygood screen resolution for ...,True
3,ORD239025,ID1449308562,2019-06-29,Bakers,"[('Thunder line', 1), ('pearTV', 2), ('Lucent ...",17260,64.30,-37.817536,144.989861,15,14735.30,Winter,False,0.9631,wife loves it. got this as a gift for my wife ...,True
4,ORD197167,ID0377544391,2019-09-04,Thompson,"[('Thunder line', 2), ('Alcon 10', 1), ('Lucen...",23180,64.98,-37.815584,144.945277,25,17449.98,Autumn,False,0.3603,super phone within days of receiving this phon...,True

In [20]:
remove = ['-', ' ']
for i in remove:
    data['date'] = [x.replace(i, '/') for x in data['date']]

t

In [11]:
data['toggle'] = ["1" for x in data['date'] if re.match(r'^\d{4}', x) is None else "ArithmeticError0"]

SyntaxError: invalid syntax (2093956523.py, line 1)

In [49]:
x = datetime.strptime(data['date'][43], '%m/%d/%Y')
datetime.strftime(x, '%Y/%m/%d')

'2019/03/13'

In [24]:
data['date'] = [datetime.strptime(x, '%m/%d/%Y') for x in data['date'] if re.search(r'^\d{4}', x)]

ValueError: time data '2019-06-22' does not match format '%m/%d/%Y'

In [25]:
def date_cleaning(data, correct_date_format):
    bad_dates = data[~data['date'].str.contains(r'^\d{4}')]
    good_dates = data[data['date'].str.contains(r'^\d{4}')]

    remove = ['-', ' ']
    for i in remove:
        bad_dates['date'] = [x.replace(i, '/') for x in bad_dates['date']]

    bad_dates['date'] = [datetime.strptime(x, '%m/%d/%Y') for x in bad_dates['date']]
    bad_dates['date'] = [datetime.strftime(x, correct_date_format) for x in bad_dates['date']]
    return pd.concat([bad_dates, good_dates])

In [5]:
output = pA.date_cleaning(df, '%Y-%m-%d')
output

c:\Users\regan\OneDrive - 22Seven Digital\5-scripts\Github\Data-Cleaning\ProjectA_ElectronicsStore_TransactionalData.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_dates['date'] = [x.replace(i, '/') for x in bad_dates['date']]
c:\Users\regan\OneDrive - 22Seven Digital\5-scripts\Github\Data-Cleaning\ProjectA_ElectronicsStore_TransactionalData.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_dates['date'] = [datetime.strptime(x, '%m/%d/%Y') for x in bad_dates['date']]
c:\Users\regan\OneDrive - 22Seven Digital\5-scripts\Github\Data-Cleaning\ProjectA_ElectronicsStore_TransactionalData.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_dates['date'] = [datetime.strftime(x, correct_date_format) for x in bad_dates['date']]

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
43,ORD473815,ID0588198721,2019-03-13,Nickolson,"[('Thunder line', 1), ('pearTV', 1)]",8490,66.07,-37.812137,144.973992,5,8131.57,Autumn,False,0.8182,awesome phone! great phone! the screen is a ni...,True
78,ORD347594,ID0332796790,2019-04-01,Bakers,"[('Lucent 330S', 2), ('pearTV', 2), ('iAssist ...",35205,73.58,-37.808563,145.000167,10,31758.08,Summer,True,0.4624,not as advertised was not actually unlocked an...,False
114,ORD293148,ID1681675856,2019-12-09,Nickolson,"[('Toshika 750', 1), ('Candle Inferno', 2)]",5180,80.53,-37.809841,144.976329,25,3965.53,Spring,False,1.1423,great build qualitygood screen resolution for ...,True
124,ORD239025,ID1449308562,2019-06-29,Bakers,"[('Thunder line', 1), ('pearTV', 2), ('Lucent ...",17260,64.30,-37.817536,144.989861,15,14735.30,Winter,False,0.9631,wife loves it. got this as a gift for my wife ...,True
136,ORD197167,ID0377544391,2019-09-04,Thompson,"[('Thunder line', 2), ('Alcon 10', 1), ('Lucen...",23180,64.98,-37.815584,144.945277,25,17449.98,Autumn,False,0.3603,super phone within days of receiving this phon...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,ORD379700,ID2190564628,2019-08-05,Nickolson,"[('Candle Inferno', 1), ('Alcon 10', 1), ('Luc...",17510,75.37,-37.816209,144.964057,5,16709.87,Winter,True,0.5513,"good quality price ratio bought it for my mom,...",True
495,ORD475510,ID0247417082,2019-08-07,Nickolson,"[('Alcon 10', 2), ('iAssist Line', 2)]",386776,59.70,-37.817662,144.970405,10,20174.70,Winter,True,0.1282,i bought this phone to send to my sister in .....,False
497,ORD079320,ID2707985442,2019-10-16,Nickolson,"[('pearTV', 1), ('Alcon 10', 1), ('Lucent 330S...",16490,106.98,-37.805979,144.966101,0,16596.98,Spring,True,1.4368,love this phone! has many great features!,True
498,ORD026546,ID0060088412,2019-05-19,Nickolson,"[('iStream', 1), ('Candle Inferno', 1), ('iAss...",5030,79.89,37.820071,144.984435,10,4606.89,Autumn,True,1.3191,spoiled son's birthday present son wanted one ...,True
499,ORD085447,ID5257193650,2019-05-25,Bakers,"[('iStream', 1), ('Toshika 750', 1), ('Alcon 1...",22370,64.62,-37.812231,144.988679,15,19079.12,Autumn,True,0.6277,two stars the phone is way smaller then it loo...,False

In [8]:
len(df[~df['date'].str.contains(r'^\d{4}')])

20

In [58]:
OUTPUT_DIR = 'G:\\My Drive\\DANIELS ECOSYSTEM\\extracurricularActivities\\DataScience\\datasets\\Transactional Retail Dataset of Electronics Store\\'
# logging.basicConfig(level=logging.WARNING, filename=f'{OUTPUT_DIR}warnings.log')

# def date_cleaning(data, correct_date_format):
#     '''
#     correct date format: YYYY-mm-dd
#     '''
#     bad_dates = data[~data['date'].str.contains(r'^\d{4}')]
#     good_dates = data[data['date'].str.contains(r'^\d{4}')]

#     remove = ['-', ' ']
#     for i in remove:
#         bad_dates['date'] = [x.replace(i, '/') for x in bad_dates['date']]

#     try:
#         bad_dates['date'] = [datetime.strptime(x, '%m/%d/%Y') for x in bad_dates['date']]
#         bad_dates['date'] = [datetime.strftime(x, correct_date_format) for x in bad_dates['date']]
#     except:
        

#     output = pd.concat([bad_dates, good_dates])

#     if len(output[~output['date'].str.contains(r'^\d{4}')]) != 0:
#         logging.warning('All faulty date formatting was not identified')

#     return output

    
# df = pd.read_csv(f'{OUTPUT_DIR}dirty_data.csv')
# date_cleaning(df, '%Y-%m-%d').to_csv(f'{OUTPUT_DIR}test_output.csv', index=False)

In [64]:
data = pd.read_csv(f'{OUTPUT_DIR}dirty_data_test.csv')

In [17]:
# df['shopping_cart'] = df['shopping_cart'].apply(lambda x: eval(x))
df.columns

Index(['order_id', 'customer_id', 'date', 'nearest_warehouse', 'shopping_cart',
       'order_price', 'delivery_charges', 'customer_lat', 'customer_long',
       'coupon_discount', 'order_total', 'season', 'is_expedited_delivery',
       'distance_to_nearest_warehouse', 'latest_customer_review',
       'is_happy_customer'],
      dtype='object')

In [20]:
OUTPUT_DIR = 'G:\\My Drive\\DANIELS ECOSYSTEM\\extracurricularActivities\\DataScience\\datasets\\Transactional Retail Dataset of Electronics Store\\'
data = pd.read_csv(f'{OUTPUT_DIR}dirty_data.csv')
data = pA.date_cleaning(data, '%Y/%m/%d')

# def product_sales_by_month(data):
#     # Analyse shopping cart

#     # isolate required fields
#     tmp_df = data[['order_id', 'customer_id', 'date', 'shopping_cart']]
#     # cleaning
#     tmp_df['shopping_cart'] = [eval(x) for x in tmp_df['shopping_cart']]
#     df_stack = tmp_df.explode('shopping_cart').reset_index()
#     df_stack['quantity'] = [x[1] for x in df_stack['shopping_cart']]
#     df_stack['shopping_cart'] = [x[0].upper() for x in df_stack['shopping_cart']]


#     df_stack['date'] = [datetime.strptime(x.replace('-', '/'), '%Y/%m/%d') for x in df_stack['date']]
#     # df_stack['date'] = [datetime.strptime(x, '%Y/%m/%d') for x in df_stack['date']]
#     df_stack = df_stack.sort_values(by='date')

#     tmp = df_stack[['date', 'shopping_cart', 'quantity']]
#     tmp['date'] = [x.to_period('M') for x in tmp['date']]
#     tmp = tmp.groupby(['date', 'shopping_cart']).sum()
#     # tmp = tmp.reset_index().to_csv(hf.create_dir(OUTPUT_DIR, 'prod_count_by_month.csv'), index=False)
#     return tmp

# product_sales_by_month(data).to_csv('C:\\Users\\regan\\OneDrive - 22Seven Digital\\1. Admin\\test.csv', index=False)

c:\Users\regan\OneDrive - 22Seven Digital\5-scripts\Github\Data-Cleaning\ProjectA_ElectronicsStore_TransactionalData.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_dates['date'] = [x.replace(i, '/') for x in bad_dates['date']]
c:\Users\regan\OneDrive - 22Seven Digital\5-scripts\Github\Data-Cleaning\ProjectA_ElectronicsStore_TransactionalData.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_dates['date'] = [datetime.strptime(x, '%m/%d/%Y') for x in bad_dates['date']]
c:\Users\regan\OneDrive - 22Seven Digital\5-scripts\Github\Data-Cleaning\ProjectA_ElectronicsStore_TransactionalData.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_dates['date'] = [datetime.strftime(x, correct_date_format) for x in bad_dates['date']]

ValueError: time data '2019/03/13' does not match format '%m/%d/%Y'

In [16]:
bad_dates = data[~data['date'].str.contains(r'^\d{4}')]
good_dates = data[data['date'].str.contains(r'^\d{4}')]

remove = ['-', ' ', '*']
for i in remove:
    bad_dates['date'] = [x.replace(i, '/') for x in bad_dates['date']]

bad_dates['date'] = [datetime.strptime(x, '%m/%d/%Y') for x in bad_dates['date']]
bad_dates['date'] = [datetime.strftime(x, '%Y/%m/%d') for x in bad_dates['date']]

C:\Users\regan\AppData\Local\Temp\ipykernel_21224\2003425733.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_dates['date'] = [x.replace(i, '/') for x in bad_dates['date']]
C:\Users\regan\AppData\Local\Temp\ipykernel_21224\2003425733.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_dates['date'] = [datetime.strptime(x, '%m/%d/%Y') for x in bad_dates['date']]
C:\Users\regan\AppData\Local\Temp\ipykernel_21224\2003425733.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bad_dates['date'] = [datetime.strftime(x, '%Y/%m/%d') for x in bad_dates['date']]

In [72]:
tmp_df = data[['order_id', 'customer_id', 'date', 'shopping_cart']]
# cleaning
tmp_df['shopping_cart'] = [eval(x) for x in tmp_df['shopping_cart']]
df_stack = tmp_df.explode('shopping_cart').reset_index()
df_stack['quantity'] = [x[1] for x in df_stack['shopping_cart']]
df_stack['shopping_cart'] = [x[0].upper() for x in df_stack['shopping_cart']]


df_stack['date'] = [datetime.strptime(x.replace('-', '/'), '%Y/%m/%d') for x in df_stack['date']]
# df_stack['date'] = [datetime.strptime(x, '%Y/%m/%d') for x in df_stack['date']]
df_stack = df_stack.sort_values(by='date')

tmp = df_stack[['date', 'shopping_cart', 'quantity']]
tmp['date'] = [x.to_period('M') for x in tmp['date']]
tmp = tmp.groupby(['date', 'shopping_cart']).sum()
tmp

# data = pA.date_cleaning(data, '%Y/%m/%d')
# product_sales_by_month(data)

C:\Users\regan\AppData\Local\Temp\ipykernel_20568\2818930102.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_df['shopping_cart'] = [eval(x) for x in tmp_df['shopping_cart']]
C:\Users\regan\AppData\Local\Temp\ipykernel_20568\2818930102.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp['date'] = [x.to_period('M') for x in tmp['date']]

In [54]:
datetime.strptime(df_stack['date'][0], '%Y-%m-%d')

datetime.datetime(2019, 3, 13, 0, 0)

In [34]:
str(df_stack['date'][0].year) + str(df_stack['date'][0].month)

'20193'

In [36]:
df_stack['yearMonth'] = [str(x.year) + str(x.month) for x in df_stack['date']]

,index,order_id,customer_id,date,shopping_cart,quantity,yearMonth
0,0,ORD473815,ID0588198721,2019-03-13,THUNDER LINE,1,20193
1,0,ORD473815,ID0588198721,2019-03-13,PEARTV,1,20193
2,1,ORD347594,ID0332796790,2019-04-01,LUCENT 330S,2,20194
3,1,ORD347594,ID0332796790,2019-04-01,PEARTV,2,20194
4,1,ORD347594,ID0332796790,2019-04-01,IASSIST LINE,1,20194
...,...,...,...,...,...,...,...
1501,497,ORD026546,ID0060088412,2019-05-19,CANDLE INFERNO,1,20195
1502,497,ORD026546,ID0060088412,2019-05-19,IASSIST LINE,2,20195
1503,498,ORD085447,ID5257193650,2019-05-25,ISTREAM,1,20195
1504,498,ORD085447,ID5257193650,2019-05-25,TOSHIKA 750,1,20195
1505,498,ORD085447,ID5257193650,2019-05-25,ALCON 10,2,20195

In [60]:

# df_stack.groupby(['yearMonth', 'shopping_cart']).sum()

C:\Users\regan\AppData\Local\Temp\ipykernel_20568\2918812847.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp['date'] = [x.to_period('M') for x in tmp['date']]

In [29]:
df['exclamation_count'] = [len(re.findall('!', x)) for x in df.latest_customer_review]
df['shopping_cart'] = df['shopping_cart'].apply(lambda x: eval(x))

       date shopping_cart  quantity
0   2019-01      ALCON 10        16
30  2019-04      ALCON 10        23